# Dataset YOLO-seg para IR (auto-generado con FastSAM)
# Este archivo se genera automáticamente en main.py

path: /zfs-home/202501029N/Terminal/F Vision/Reentreno/data
train: ir
val: ir

nc: 1
names:
  0: object
